blank_issues_enabled: true
contact_links:
  - name: RadhaX Support
    url: https://t.me/RadhaXSupport
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://RadhaX.tech/
    about: Documentation for getting started with bot.
